insert into countries (name) values ('Argentina');
insert into countries (name) values ('Uruguay');
insert into countries (name) values ('Colombia');
insert into pet_types ( name) values ('Perro');
insert into pet_types ( name) values ('Gato');
insert into pet_types ( name) values ('Hamster');
insert into pet_types ( name) values ('Tortuga');
insert into pet_types ( name) values ('Pez');
insert into cities (name,country_id ) values('Bogota',3);
insert into cities (name,country_id) values ('Buenos Aires',1);
insert into cities (name,country_id) values ('Montevideo',2);
insert into cities (name,country_id ) values('Barranquilla',3);
insert into cities (name,country_id ) values('Pasto',3);
insert into cities (name,country_id) values ('Cordoba',1);
insert into breeds (name,pet_type_id) values ('Lobo siberiano + Chiguagua',1);
insert into breeds (name,pet_type_id) values ('Bulldog',1);
insert into breeds (name,pet_type_id) values ('Gato de pelo corto',2);
insert into breeds (name,pet_type_id) values ('Gato siamés',2);
insert into breeds (name,pet_type_id) values ('Cuy Pastusense',3);
insert into users (name,email,password,image,city_id) values ('Kenneth','kennethleo1@hotmail.com','1234','kenneth.jpg',1);
insert into users (name,email,password,image,city_id) values ('Juan Pablo','acostajuan678@gmail.com','123','juampi-jpg',2);
insert into pets (name,age,sex,breed_id,status,number_of_vaccines,city_id,description,image,attitude) values ('Max',1,'Macho',1,'false',2,1,'Max es un perro muy cariñoso y juguetón.','perro1.jpg','Hogareño');
insert into pets (name,age,sex,breed_id,status,number_of_vaccines,city_id,description,image,attitude) values ('Neku',2,'Macho','3','false',2,3,'Neku Es un gato muy tranquilo y no maulla mucho.','gato1.jpg','Tranquilo');
insert into pets (name,age,sex,breed_id,status,number_of_vaccines,city_id,description,image,attitude) values ('Roger',1,'Macho','5','false',2,5,'Roger es un hamster muy inquieto a la hora de jugar.','hamster1.jpg','Inquieto');
insert into orders (user_id,pet_id) values (1,3);
insert into orders (user_id,pet_id) values (2,1);